apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp-staging

namespace: staging

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: webapp
    path: deployment-json-patch.yaml

configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
      - environment=staging
      - debug=true

secretGenerator:
  - name: webapp-secrets
    literals:
      - database-password=staging-secret-password
      - api-key=staging-api-key-12345

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: nginx
    newTag: 1.21-alpine

replicas:
  - name: webapp
    count: 2