apiVersion: v2
name: my-blog
description: A comprehensive WordPress blog application with MariaDB backend showcasing Helm features
home: https://github.com/my-org/my-blog
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - wordpress
  - blog
  - cms
  - php
  - mariadb
  - mysql
maintainers:
  - name: DevOps Team
    email: devops@example.com
sources:
  - https://github.com/WordPress/WordPress
  - https://github.com/MariaDB/server

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "6.4.2"
