apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-blog
data:
  uploads.ini: |
    file_uploads = On
    memory_limit = 256M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 300
    max_input_vars = 3000
