apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    spec:
      containers:
        - name: webapp
          env:
            - name: ENABLE_LOGGING
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
