apiVersion: batch/v1
kind: CronJob
metadata:
  name: hellocron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hellocron
            image: busybox
            args:
            - /bin/sh
            - -c
            - "date; echo Hello from your Kubernetes cluster"
          restartPolicy: OnFailure
  suspend: false
