kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: esdata
          hostPath:
            path: /data/esdata
            type: DirectoryOrCreate
      initContainers:
        - name: busybox
          image: busybox:1.28
          command:
            ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: esdata
              mountPath: "/usr/share/elasticsearch/data"
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.4
          ports:
            - name: es1
              containerPort: 9200
            - name: es2
              containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1g"
            - name: cluster.name
              value: "elasticsearch"
            - name: node.name
              value: "elasticsearch-0"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: esdata
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - protocol: TCP
      name: es1
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: es2
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: analytics
  labels:
    app: analytics

spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: kibana:7.17.4
          ports:
            - name: analytics
              containerPort: 5601
          env:
            - name: SERVER_NAME
              value: "analytics"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.default.svc.cluster.local:9200"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-svc
spec:
  type: NodePort
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30883

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: analytics-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`analytics.upskillforge.com`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: analytics-svc
          port: 5601

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: analytics-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`analytics.upskillforge.com`)
      kind: Rule
      services:
        - name: analytics-svc
          port: 5601
  tls:
    certResolver: default

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true

# Access Kibana at: https://analytics.upskillforge.com
# HTTP requests will be automatically redirected to HTTPS
# Or access directly via: http://195.179.227.12:30883 (NodePort still available as backup)