apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

#kubectl set image deployment/web-server nginx=nginx:1.18
#while true; do curl http://<Service-IP>/; sleep 1; done
#kubectl set image deployment/web-server nginx=nginx:wrong-tag