apiVersion: v1
kind: Namespace
metadata:
  name: quota-exercise-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: quota-exercise-ns
spec:
  hard:
    requests.cpu: "1"  # Total amount of CPU that can be requested
    requests.memory: 1Gi  # Total amount of memory that can be requested
    limits.cpu: "2"  # Total amount of CPU that can be used as a limit
    limits.memory: 2Gi  # Total amount of memory that can be used as a limit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: quota-exercise-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: "800Mi"
            cpu: "0.5"
          limits:
            memory: "800Mi"
            cpu: "0.5"
