apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.4

#kubectl set image deployment/nginx-deployment nginx=nginx:1.18
#kubectl rollout status deployment/nginx-deployment
#kubectl rollout undo deployment/nginx-deployment