apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-gce-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-gce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
