apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
spec:
  clusterIP: None
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080

#Le service ne reçoit pas d’IP de cluster, et la résolution DNS de my-headless-service 
#retournera toutes les IP des pods ayant le label app: my-app