apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hw-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: helloworld
          image: karthequian/helloworld:black
          ports:
            - containerPort: 80