apiVersion: v1
kind: Namespace
metadata:
  name: training
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: training
data:
  title: Hello
  message: How are you ?
  app.properties: |
    title=Hello
    message=How are you ?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  namespace: training
spec:
  selector:
    matchLabels:
      app: hw
  replicas: 1
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: karthequian/helloworld:latest
        env: 
          - name: PG_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: example-config
                key: title
          - name: PG_DB_URL
            valueFrom:
              configMapKeyRef:
                name: example-config
                key: message
        volumeMounts:
          - name: config-volume
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: config-volume
          configMap: 
            name: example-config

