apiVersion: v1
kind: Namespace
metadata:
  name: training
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: training
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded value of 'username'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  namespace: training
spec:
  selector:
    matchLabels:
      app: hw
  replicas: 1
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: karthequian/helloworld:latest
        env: 
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
        volumeMounts:
          - name: my-secret-volume
            mountPath: "/etc/secret"
            readOnly: true
      volumes:
        - name: my-secret-volume
          secret:
            secretName: my-secret

