apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  clusterID: [cluster-id]
  pool: [pool-name]
  imageFormat: "2"
  imageFeatures: "layering"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        env:
          - name: POSTGRES_USER
            value: "db"
          - name: POSTGRES_PASSWORD
            value: "db"
          - name: POSTGRES_DB
            value: "db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: db-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 6543
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
