apiVersion: v1
kind: Pod
metadata:
  name: test-gce-pod
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-gce
      name: test-volume
      readOnly: false
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-gce-pvc
