apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
  labels:
    name: foo-pv-claim
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
