apiVersion: v1
kind: Pod
metadata:
  name: foo-pod
spec:
  containers:
    - name: foo-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: foo-volume
          mountPath: /data
          readOnly: false
  volumes:
    - name: foo-volume
      persistentVolumeClaim:
        claimName: foo-pvc
