apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: foo-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: foo-pv-claim
