apiVersion: v1
kind: Namespace
metadata:
  name: training

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: training
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.nvidia.com/gpu: 4
# kubectl get resourcequota -n training
# kubectl describe resourcequota compute-resources -n training

