apiVersion: v1
kind: Pod
metadata:
  name: test-quota
  namespace: training
spec:
  containers:
    - name: test
      image: nginx
      resources:
        requests:
          cpu: "600m"
          memory: "600Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
