apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

metadata:
  name: redis-component

resources:
  - redis-deployment.yaml
  - redis-service.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  cache: redis
  component: redis
