replicaCount: 1

image:
  repository: registry
  tag: "2.8.3"
  pullPolicy: IfNotPresent

service:
  name: registry
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - registry.upskillforge.com
  paths:
    - /
  tls: []

persistence:
  enabled: true
  size: 100Gi
  storageClass: "hetzner-smb-storage"
  accessMode: ReadWriteOnce

# Registry configuration
configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    filesystem:
      rootdirectory: /var/lib/registry
    delete:
      enabled: true
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
    debug:
      addr: :5001
      prometheus:
        enabled: true
        path: /metrics

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
