expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.upskillforge.com
    className: "traefik"

externalURL: https://harbor.upskillforge.com

harborAdminPassword: "WeusCloud2025!!"

persistence:
  enabled: true
  resourcePolicy: "retain"
  persistentVolumeClaim:
    registry:
      storageClass: "hetzner-smb-storage"
      size: 50Gi
    jobservice:
      storageClass: "hetzner-smb-storage"
      size: 1Gi
    database:
      storageClass: "hetzner-smb-storage"
      size: 10Gi
    redis:
      storageClass: "hetzner-smb-storage"
      size: 1Gi
    trivy:
      storageClass: "hetzner-smb-storage"
      size: 5Gi
