apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-smb-storage
provisioner: smb.csi.k8s.io
parameters:
  source: "//u474420.your-storagebox.de/backup"
  csi.storage.k8s.io/provisioner-secret-name: "hetzner-smb-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "registry"
  csi.storage.k8s.io/node-stage-secret-name: "hetzner-smb-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "registry"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - vers=2.1
  - uid=999
  - gid=999
  - sec=ntlmssp
  - file_mode=0600
  - dir_mode=0700
  - noperm
