apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 34.79.219.176/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - public-ip-pool
