kong:
  env:
    PROXY_LISTEN: 0.0.0.0:8443 http2 ssl
    ADMIN_LISTEN: 0.0.0.0:8444 http2 ssl
    STATUS_LISTEN: 0.0.0.0:8100
  proxy:
    statusContainerPort: 8100
  admin:
    addresses:
      - 0.0.0.0
  status:
    addresses:
      - 0.0.0.0
