{{- if not .Values.wordpress.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-blog.wordpress.secretName" . }}
  labels:
    {{- include "my-blog.wordpress.labels" . | nindent 4 }}
  {{- with (include "my-blog.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.wordpress.auth.password }}
  wordpress-password: {{ .Values.wordpress.auth.password | b64enc | quote }}
  {{- else }}
  wordpress-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}