apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp-development

namespace: development

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
      - environment=development
      - debug=true

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: nginx
    newTag: 1.21-alpine