apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp-production-full-stack

namespace: production

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml

# Using multiple components together
components:
  - ../../components/redis
  - ../../components/logging

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
      - environment=production
      - debug=false
      - cache_enabled=true
      - logging_enabled=true

namePrefix: prod-

commonLabels:
  environment: production
  tier: frontend

images:
  - name: nginx
    newTag: 1.21
  - name: redis
    newTag: 7-alpine

replicas:
  - name: webapp
    count: 3
